name: RedStoneMe
main: me.crylonz.RedStoneMe
version: ${version}
author: Crylonz
softdepend: [Multiverse-Core]
description: RedStone enable when your a near
api-version: 1.13
commands:
  redstoneme:
    description: all commands of redstoneme
    usage: /redstoneme help|new|destroy|info|tp|rename|move|toggle|action|add|remove|clearplayers|who|radius|state|public|setowner|list|reload|debug
  rsm:
    description: Register a block to redstone it
    usage: /rsm help|new|destroy|info|tp|rename|move|toggle|action|add|remove|clearplayers|who|radius|state|public|setowner|list|reload|debug
permissions:
  redstoneme.*:
    description: Gives access to all redstoneme commands
    children:
      redstoneme.new: true
      redstoneme.destroy: true
      redstoneme.add: true
      redstoneme.remove: true
      redstoneme.action: true
      redstoneme.help: true
      redstoneme.list: true
      redstoneme.radius: true
      redstoneme.state: true
      redstoneme.public: true
      redstoneme.info: true
      redstoneme.tp: true
      redstoneme.rename: true
      redstoneme.move: true
      redstoneme.reload: true
      redstoneme.debug: true
  redstoneme.new:
    description: Allows player to generate a new trigger
    default: op
  redstoneme.destroy:
    description: Allows player to destroy a existing trigger
    default: op
  redstoneme.list:
    description: Allows player to see list of trigger and player per trigger
    default: op
  redstoneme.add:
    description: Allows player to add a player to a trigger
    default: op
  redstoneme.remove:
    description: Allows player to remove a player to a trigger
    default: op
  redstoneme.action:
    description: Allows player to edit the action of a trigger
    default: op
  redstoneme.help:
    description: Allows player to see help
    default: op
  redstoneme.radius:
    description: Allows player to edit the radius of a trigger
    default: op
  redstoneme.state:
    description: Allows player to edit the state of a trigger
    default: op
  redstoneme.public:
    description: Allows player to make a trigger public
    default: op
  redstoneme.info:
    description: Allows player to inspect a trigger
    default: op
  redstoneme.tp:
    description: Allows player to teleport to a trigger
    default: op
  redstoneme.rename:
    description: Allows player to rename a trigger
    default: op
  redstoneme.move:
    description: Allows player to move a trigger
    default: op
  redstoneme.reload:
    description: Allows player to reload the configuration
    default: op
  redstoneme.debug:
    description: Allows player to enable debug logging
    default: op
  redstoneme.admin:
    description: Allows player to access to all trigger
    default: op
